#!/bin/ksh

# cmd paste_link %{{
# 	IFS='
# '
# 	# TODO: reescribir no con los marcados a copiar/pegar,
# 	# sino con los seleccionados: $fs
# 	set -- $(cat ~/.local/share/lf/files)
# 	mode="$1"
# 	shift
# 	if [ $# -lt 1 ]; then
# 		lf -remote "send $id echo no files to link"
# 		exit 1
# 	fi
# 	case "$mode" in
# 		# symbolically copy mode is indicating a soft link
# 		copy) ln -sr -t . -- "$@";;
# 		# while a move mode is indicating a hard link
# 		move) ln -t . -- "$@";;
# 	esac \
# 		|| exit $?
# 	rm ~/.local/share/lf/files
# 	lf -remote "send clear"
# }}
