#!/bin/sh

log_i() {
    echo "-> $1"
}

value_from_column() {
    separator=' '

    if [ "$3" != "" ]; then
        separator="$3"
    fi

    echo "$1" | awk -F "$separator" "{print \$$2}" | awk '{$1=$1};1'
}

if [ "$1" = "-s" ]; then
    shift
else
    log_i "fazendo login no vault para obter credenciais"
fi

vault login -method=github -address=https://vault.prod.contaazul.com token="$GITHUB_TOKEN" > /dev/null &&

case "$1" in
    "SE")
        vault_url="database/creds/search-engine-core-datareader"
        host="contaazul-ro3-rds.prod.contaazul.local"
        port="5432"
        database="contaazul" ;;
    "PA")
        vault_url="database/creds/payments-datareader"
        host="payments-rds.prod.contaazul.local"
        port="5432"
        database="payments" ;;
    *) echo "erro: acrônimo inválido" && return 1 ;;
esac

login_info="$(vault read $vault_url)"

user_line=$(echo "$login_info" | grep 'username')
pass_line=$(echo "$login_info" | grep 'password')

sec_user=$(value_from_column "$user_line" 2)
sec_pass=$(value_from_column "$pass_line" 2)

printf "postgres://$sec_user:$sec_pass@$host:$port/$database"
