#!/bin/sh

# Path to the key file.  One line with a long random password
KFILE=/root/discenc.key
# Modify to your needs
DUID_DISK=33936b7dbd03d222
# Modify to your needs
DUID_CRYPT=539d3e3e2a3023e4

# Mountpoints
# set -A MP -- /home /home/browser
set -A MP -- /mnt/secretstuff
# Corresponding disk slices.  Make sure the order matches the order
# of the mountpoints above
# set -A SLICE -- a d
set -A SLICE -- a

if [ ! -f $KFILE ]; then
    echo "$KFILE not found. Cannot mount $MP"
    exit 1
fi

sync

bioctl -c C -l ${DUID_DISK}.a -p $KFILE softraid0 || exit 1

i=0
for part in ${MP[@]}; do
    # fsck -p ${DUID_CRYPT}.${SLICE[i]}
    fsck -p ${DUID_CRYPT}.i

    if [ $? -gt 0 ]; then
        echo "fsck failed for ${part}.  Check manually"
        break
    fi

    # mount -o noatime,softdep ${DUID_CRYPT}.${SLICE[i]} $part
    mount -o noatime,softdep ${DUID_CRYPT}.i $part
    logger "Mounted $part"

    i=$((i+1))
done


#!/bin/sh

# echo "$(whoami)"

# [ "$UID" -eq 0 ] || exec doas "$0" "$@"

# sd2a
# phisical_device=33936b7dbd03d222.a

# sd4i
# virtual_device=539d3e3e2a3023e4.i

# doas bioctl -c C -l $phisical_device softraid0
# doas mount $virtual_device /mnt/secretstuff

# umount /mnt/secretstuff
# bioctl -d sd4
