#!/bin/sh

out="$1"
shift

case "$out" in
    *.tar.bz2|*.tbz2) tar cjvf "$out" "$@" ;;
    *.tar.gz|*.tgz)   tar czvf "$out" "$@" ;;
    *.tar.xz|*.txz)   tar cJvf "$out" "$@" ;;
    *.tar)            tar cvf  "$out" "$@" ;;
    *.zip)            zip -r "$out" "$@" ;;
    *.rar)            rar a "$out" "$@" ;;
    *.7z)             7z a "$out" "$@" ;;
    *) echo "compress: unknown archive type: $out" >&2; exit 1 ;;
esac
