#!/bin/ksh

# todo: verificar se já existe arquivo/pasta com aquele nome

# Check if the input ends with a /
if [[ $1 == @(*/) ]] ; then
    mkdir -p "$1"
else
    # Input doesn't end with /, so create a file
    touch "$1"
fi
