#!/bin/ksh

set -f

clear
# clear; tput cup $(($(tput lines)/3)); tput bold

printf "\n\t%s" "$@"
printf "\n\ndelete?[y/N]"
# printf -- "%s\n" $fx | sed 's|'"$HOME"'||'
# printf "\t\033[1;33m¿Remover? \033[37m[\033[32ms\033[37m/\033[31mN\033[37m]\033[m "

read -r ans

if [ $ans = "y" ] ; then
    rm -rf -- "$@"
fi
# case "$REPLY" in
#     [yYsS]) rm -rf -- $fx ;;
# esac
