#!/bin/sh

# extract the current file with the right command
# (xkcd link: https://xkcd.com/1168/)

set -f

case "$@" in
    *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf "$@";;
    *.tar.gz|*.tgz) tar xzvf "$@";;
    *.tar.xz|*.txz) tar xJvf "$@";;
    *.zip) unzip "$@";;
    *.rar) unrar x "$@";;
    *.7z) 7z x "$@";;
esac

# cmd extract ${{
# 	clear; tput cup $(($(tput lines)/3)); tput bold
# 	set -f
# 	printf "%s\n\t" "$fx"
# 	printf "extract?[y/N]"
# 	read ans
# 	[ $ans = "y" ] && aunpack $fx
# }}

# cmd extract ${{
# 	clear; tput cup $(($(tput lines)/3)); tput bold
# 	set -f
# 	printf -- "%s\n" $fx
# 	printf "\t\033[1;34m¿Extraer? \033[37m[\033[32ms\033[37m/\033[31mN\033[37m]\033[m "
# 	read -r REPLY
# 	case "$REPLY" in
# 		[yYsS]) aunpack $fx ;;
# 	esac
# }}

