#!/bin/sh
# extract <archive> — unpack by extension (https://xkcd.com/1168/).

set -f

case "$1" in
    *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf "$1" ;;
    *.tar.gz|*.tgz)                  tar xzvf "$1" ;;
    *.tar.xz|*.txz)                  tar xJvf "$1" ;;
    *.tar)                           tar xvf  "$1" ;;
    *.zip)                           unzip "$1" ;;
    *.rar)                           unrar x "$1" ;;
    *.7z)                            7z x "$1" ;;
    *.gz)                            gunzip "$1" ;;
    *.bz2)                           bunzip2 "$1" ;;
    *) echo "extract: unknown archive type: $1" >&2; exit 1 ;;
esac
