#!/bin/sh

in="$(mktemp)"; out="$(mktemp)"
trap 'rm -f "$in" "$out"' EXIT

cat > "$in"

dim="$(xdpyinfo | awk '/dimensions/{print $2}' | sed 's/x/ /')"
w="${dim% *}"; h="${dim#* }"
xoff=$(( w / 2 - 150 )); yoff=$(( h / 2 - 90 ))

st -i -g 50x30+"$xoff"+"$yoff" -e sh -c "fzf $* < '$in' > '$out'"

cat "$out"
