#!/bin/sh

set -e

SEL_FILE="/tmp/sel_items"

[ ! -f "$SEL_FILE" ] && touch "$SEL_FILE"

increment_only=false
show_selected=false

while [ "$#" -gt 0 ]; do
    case "$1" in
        --increment-only)
            increment_only=true
            break;;
        --show-selected)
            show_selected=true
            break;;
        # TODO
        # --use-selected-only)
        #     use_selected_only=true
        #     break;;
        *)
            break;;
    esac
done

[ "$show_selected" = true ] && cat "$SEL_FILE" && exit 0

[ ! "$increment_only" = true ] && cat /dev/null > "$SEL_FILE"

temp="$(mktemp)"

eza --group-directories-first --icons always -a | fzf -m \
    --bind 'tab:toggle+clear-query' \
    --bind 'shift-tab:toggle-all+clear-query' \
    --height 100% \
    --color=bg+:-1 \
    --border=sharp \
    --info=inline \
    --reverse \
    --preview='echo {} | sed s/^..// | xargs preview' >> $temp

if [ "$(cat $temp)" != "" ];then
    cat "$temp" | sed 's/^..//' | xargs readlink -f | tee -a "$SEL_FILE"
fi

[ "$1" != "" ] && eval "cat $SEL_FILE | xargs -I {} $@ {}"
