#!/bin/sh

if [ -n "$NVIM_SOCKET" ]; then
    nvr --servername 127.0.0.1:$NVIM_SOCKET "$@"
else
    available_port=$(get_available_port "6660")
    nvim --listen 127.0.0.1:$available_port --cmd "let g:current_port='$available_port'" "$@"
fi
