#!/bin/sh

if [ -n "$NVIM_SOCKET" ]; then
    command nvim --server 127.0.0.1:$NVIM_SOCKET --remote "$@"
else
    available_port=$(get_available_port "6660")
    command nvim --listen 127.0.0.1:$available_port --cmd "let g:current_port='$available_port'" "$@"
fi
