#!/bin/sh

if [ -n "$NVIM" ] && [ "$#" -gt 0 ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/sh/lib/guard.sh"
    n=$#
    while [ "$n" -gt 0 ]; do set -- "$@" "$(abspath "$1")"; shift; n=$((n - 1)); done
    exec nvim --server "$NVIM" --remote "$@"
else
    exec nvim "$@"
fi
