#!/bin/sh
[ "$(id -u)" -eq 0 ] || exec doas "$0" "$@"

KFILE=/root/discenc.key
DUID_DISK=33936b7dbd03d222
DUID_CRYPT=539d3e3e2a3023e4
MOUNTPOINT=/mnt/secretstuff

[ -f "$KFILE" ] || { echo "$KFILE not found. Cannot mount $MOUNTPOINT" >&2; exit 1; }

sync
bioctl -c C -l "${DUID_DISK}.a" -p "$KFILE" softraid0 || exit 1

fsck -p "${DUID_CRYPT}.i" || { echo "fsck failed for $MOUNTPOINT. Check manually" >&2; exit 1; }
mount -o noatime,softdep "${DUID_CRYPT}.i" "$MOUNTPOINT"
logger "Mounted $MOUNTPOINT"

# manual procedure (recovery):
# physical_device=33936b7dbd03d222.a   (sd2a)
# crypto_device=539d3e3e2a3023e4.i     (sd4i)
# doas bioctl -c C -l $physical_device softraid0
# doas mount $crypto_device /mnt/secretstuff
# umount /mnt/secretstuff
# bioctl -d sd4
