#!/usr/local/bin/bash

export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

file="$(fzf --preview 'bat --color always {}' | sed 's/ /\\ /g')"

if [ -n "$file" ]; then
    full_path="$(realpath $file)"

    file_folder="$(dirname <<< $full_path)"

    repo_path="$(git -C $file_folder rev-parse --show-toplevel)"

    if $? -eq 0; then
        cd $repo_path
    fi

    nvim $full_path
fi

# #!/bin/zsh
#
# export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
#
# file="$(fzf --preview 'bat --color always {}' | sed 's/ /\\ /g')"
#
# if [ "$file" != "" ]; then
#     current_path="$(pwd)"
#
#     full_path="$current_path/$file"
#
#     file_folder="$(dirname $full_path)"
#
#     cd $file_folder
#
#     cd $(git rev-parse --show-toplevel || pwd)
#
#     echo $full_path
#
#     nvim $full_path
# fi
