#!/bin/sh

# depends on xclip

EDITOR="$1"
TEMPFILE="$(mktemp)"

xclip -selection clipboard -o >> "$TEMPFILE"

eval "$EDITOR $TEMPFILE"

# xclip -selection clipboard -target text/plain -i "$TEMPFILE"
cat "$TEMPFILE" | xsel -i -b

# xdotool key --window %2 --clearmodifiers "ctrl+v"

rm "$TEMPFILE"
