#!/bin/sh

set -e

# TODO
# flag para não limpar o arquivo de seleção (apenas incrementar)
# flag para listar o que tá selecionado
# flag para apenas usar o que tá selecionado (sem incrementar)
# preview para pastas

SEL_FILE="/tmp/sel_items"

[ ! -f "$SEL_FILE" ] && touch "$SEL_FILE"

cat /dev/null > "$SEL_FILE"

temp="$(mktemp)"

eza --group-directories-first --icons always -a | fzf -m \
    --bind 'ctrl-v:toggle+clear-query' \
    --bind 'alt-v:toggle-all+clear-query' \
    --height 100% \
    --color=bg+:-1 \
    --border=sharp \
    --info=inline \
    --reverse \
    --preview='echo {} | sed s/^..// | xargs preview' >> $temp

if [ "$(cat $temp)" != "" ];then
    cat "$temp" | sed 's/^..//' | xargs readlink -f | tee -a "$SEL_FILE"
fi

if [ "$1" != "" ]; then
    eval "cat $SEL_FILE | xargs -I {} $@ {}"
fi
