#!/bin/sh

set -e

# TODO
# flag para não limpar o arquivo de seleção (apenas incrementar)
# flag para listar o que tá selecionado
# flag para apenas usar o que tá selecionado (sem incrementar)
# preview para pastas

SEL_FILE="/tmp/sel_items"

[ ! -f "$SEL_FILE" ] && touch "$SEL_FILE"

cat /dev/null > "$SEL_FILE"

item_list="$(eza --group-directories-first --icons always)"

lines="$(echo "$item_list" | wc -l)"

echo "$item_list" | fzf -m \
    --height $(expr $lines + 2) \
    --bind 'ctrl-v:toggle+clear-query' \
    --bind 'alt-v:toggle-all+clear-query' \
    --color=bg+:-1 \
    --border=horizontal \
    --info=inline \
    --reverse \
    --preview='echo {} | sed s/^..// | xargs preview' >> $SEL_FILE

if [ "$(cat $SEL_FILE)" != "" ];then
    cat "$SEL_FILE" | sed 's/^..//' | xargs readlink -f | tee -a "$SEL_FILE"
fi

if [ "$1" != "" ]; then
    eval "cat $SEL_FILE | xargs $1"
fi
