#!/bin/sh

local_mirror=/mnt/secretstuff/
external_mirror=/mnt/external_backup_drive/
files=exclude_from_sync.txt

#TODO: verificar se a pasta de destino ja possui driver montado
doas ntfs-3g /dev/sd3i $external_mirror || echo "mount failed"

doas rsync -Dlrtvh --progress --size-only --delete --exclude-from=$files $local_mirror $external_mirror || echo "sync failed"

doas umount $external_mirror || echo "umount failed"
