#!/bin/sh
set -e

local_mirror=/mnt/secretstuff/
external_mirror=/mnt/external_backup_drive/
exclude="$HOME/.local/scripts/exclude_from_sync.txt"
device=/dev/sd3i

mount | grep -q "$external_mirror" || doas ntfs-3g "$device" "$external_mirror"
doas rsync -Dlrtvh --progress --size-only --delete --exclude-from="$exclude" "$local_mirror" "$external_mirror"
doas umount "$external_mirror"
