#!/bin/sh

# Modify to your needs
DUID_CRYPT=539d3e3e2a3023e4

# Mountpoints to unmount
set -A MP -- /mnt/secretstuff

sync

for part in ${MP[@]}; do
    echo -n "Unmount $part "
    logger "Unmount $part"
    umount -f $part
    echo "done."
    sync
done

bioctl -d ${DUID_CRYPT}
