#!/bin/sh
[ "$(id -u)" -eq 0 ] || exec doas "$0" "$@"

DUID_CRYPT=539d3e3e2a3023e4
MOUNTPOINT=/mnt/secretstuff

sync
logger "Unmount $MOUNTPOINT"
umount -f "$MOUNTPOINT" && printf 'unmounted %s\n' "$MOUNTPOINT"
sync

bioctl -d "$DUID_CRYPT"
