#!/bin/sh

case "$1" in
        --help | -h)
                echo "Prune docker volumes, build caches, dangling images and containers, unused networks."
                echo "Use -f to force/skip confirmation"
                return
        ;;
esac

docker system prune $1
docker rmi $1 $(docker images -q)
docker buildx prune $1
docker volume prune $1
docker network prune $1
